import os
import json
import logging
import base64
import stripe
from datetime import datetime
from dotenv import load_dotenv
import google.generativeai as genai
import requests
from database import get_db

load_dotenv()
logger = logging.getLogger(__name__)
stripe.api_key = os.environ.get("STRIPE_SECRET_KEY")

HTML_REPORT_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  body {{ font-family: 'Segoe UI', sans-serif; padding: 40px; color: #1a1a2e; max-width: 800px; margin: 0 auto; }}
  .header {{ border-bottom: 3px solid #6366f1; padding-bottom: 20px; margin-bottom: 30px; }}
  .header h1 {{ color: #6366f1; margin: 0 0 5px; font-size: 22px; }}
  .meta {{ color: #64748b; font-size: 13px; }}
  .section {{ margin-bottom: 25px; }}
  .section h2 {{ color: #334155; font-size: 15px; text-transform: uppercase;
                 letter-spacing: 1px; border-bottom: 1px solid #e2e8f0; padding-bottom: 8px; }}
  .field {{ display: flex; gap: 15px; padding: 8px 0; border-bottom: 1px solid #f1f5f9; }}
  .field-label {{ color: #64748b; font-size: 13px; min-width: 180px; }}
  .field-value {{ color: #1e293b; font-size: 13px; font-weight: 500; }}
  .badge {{ display: inline-block; padding: 2px 10px; border-radius: 20px; font-size: 11px; font-weight: 700; }}
  .badge-complete {{ background: #dcfce7; color: #16a34a; }}
  .badge-flag {{ background: #fef2f2; color: #dc2626; }}
  .upsell {{ background: #f0f9ff; border: 1px solid #0ea5e9; border-radius: 8px; padding: 15px; margin-top: 10px; }}
  .upsell h3 {{ color: #0369a1; margin: 0 0 8px; font-size: 14px; }}
  .footer {{ text-align: center; color: #94a3b8; font-size: 12px; margin-top: 40px; border-top: 1px solid #e2e8f0; padding-top: 20px; }}
</style>
</head>
<body>
<div class="header">
  <h1>Service Report — {business_name}</h1>
  <div class="meta">
    Report ID: {report_id} &bull;
    Date: {date} &bull;
    Provider: {provider_name}
  </div>
</div>

<div class="section">
  <h2>Client & Appointment Details</h2>
  <div class="field"><span class="field-label">Client Name</span><span class="field-value">{client_name}</span></div>
  <div class="field"><span class="field-label">Service Performed</span><span class="field-value">{service}</span></div>
  <div class="field"><span class="field-label">Duration</span><span class="field-value">{duration}</span></div>
  <div class="field"><span class="field-label">Status</span><span class="badge badge-complete">Completed</span></div>
  {extra_fields}
</div>

<div class="section">
  <h2>Service Notes</h2>
  <p style="color:#334155;line-height:1.7;">{service_notes}</p>
</div>

{compliance_section}

{upsell_section}

<div class="section">
  <h2>Next Steps</h2>
  <p style="color:#334155;">{next_steps}</p>
</div>

<div class="footer">
  Generated by Scale With Jak Automations &bull; {business_name} &bull; {date}
</div>
</body>
</html>
"""


class FieldReportAgent:
    """
    Converts voice notes and job photos into professional service reports and Stripe invoices.
    Works for both MedSpas (treatment reports) and Vet Clinics (SOAP notes, post-op reports).
    """

    def __init__(self):
        gemini_key = os.environ.get("GEMINI_API_KEY")
        if gemini_key:
            genai.configure(api_key=gemini_key)
        self.model = genai.GenerativeModel("gemini-2.5-flash")
        self.vision_model = genai.GenerativeModel("gemini-2.5-flash")
        self.resend_key = os.environ.get("RESEND_API_KEY")
        self.from_email = os.environ.get("SMTP_EMAIL", "reports@scalewithjak.com")
        self.db = get_db()

    def transcribe_voice_note(self, voice_text):
        """
        Cleans up a raw voice transcription into structured service data.
        Input is the raw transcript (e.g., from Whisper or phone dictation).
        """
        prompt = f"""
        You are a medical/veterinary scribe. Clean up this raw voice note into structured data.
        Extract all relevant clinical and service information.

        Raw voice note:
        "{voice_text}"

        Return JSON:
        {{
          "service_performed": "...",
          "duration_mins": int or null,
          "findings": "clinical findings or treatment notes",
          "products_used": ["item1", "item2"],
          "units_used": {{"item": quantity}},
          "follow_up_required": bool,
          "follow_up_notes": "...",
          "upsell_opportunity": "any upsell opportunity noticed during service or null",
          "compliance_flags": ["any regulatory items to document"]
        }}
        """

        try:
            response = self.model.generate_content(
                contents=f"Return ONLY valid JSON.\n\n{prompt}"
            )
            clean = response.text.replace("```json", "").replace("```", "").strip()
            return json.loads(clean)
        except Exception as e:
            logger.error(f"Voice transcription parsing failed: {e}")
            return {}

    def analyze_job_photo(self, image_path_or_base64):
        """
        Uses Gemini Vision to analyze a job/treatment photo.
        Works for both before/after medspa photos and vet procedure photos.
        """
        try:
            if os.path.exists(str(image_path_or_base64)):
                with open(image_path_or_base64, "rb") as f:
                    image_data = base64.b64encode(f.read()).decode("utf-8")
            else:
                image_data = image_path_or_base64

            image_part = {
                "inline_data": {
                    "mime_type": "image/jpeg",
                    "data": image_data
                }
            }

            prompt = """Analyze this service/treatment photo and provide:
            1. What procedure or service is visible
            2. Any quality or compliance observations
            3. Whether this is a before or after photo (if determinable)
            4. Any follow-up care indicators

            Return JSON: {"procedure_visible": "...", "quality_notes": "...", "photo_type": "before/after/during/other", "follow_up_indicators": [...]}
            """

            response = self.vision_model.generate_content([image_part, prompt])
            clean = response.text.replace("```json", "").replace("```", "").strip()
            return json.loads(clean)
        except Exception as e:
            logger.warning(f"Photo analysis failed (non-critical): {e}")
            return {}

    def generate_report(self, report_data, niche="veterinary clinic"):
        """
        Assembles the full HTML service report from structured data.
        report_data: {business_name, provider_name, client_name, service_data, photo_analysis, niche_extras}
        """
        business = report_data.get("business_name", "")
        provider = report_data.get("provider_name", "")
        client = report_data.get("client_name", "")
        service_data = report_data.get("service_data", {})
        photo = report_data.get("photo_analysis", {})
        report_id = f"RPT-{datetime.utcnow().strftime('%Y%m%d-%H%M%S')}"

        # Build extra fields (niche-specific)
        extra_fields = ""
        if niche.lower() == "veterinary clinic":
            pet_name = report_data.get("pet_name", "")
            species = report_data.get("species", "")
            if pet_name:
                extra_fields += f'<div class="field"><span class="field-label">Patient (Pet)</span><span class="field-value">{pet_name} ({species})</span></div>'

        # Compliance section
        flags = service_data.get("compliance_flags", [])
        if flags:
            flags_html = "".join(f'<span class="badge badge-flag" style="margin:3px">{f}</span> ' for f in flags)
            compliance_section = f"""
            <div class="section">
              <h2>Compliance Checklist</h2>
              <p>Items documented for regulatory compliance:</p>
              {flags_html}
            </div>"""
        else:
            compliance_section = ""

        # Upsell section
        upsell = service_data.get("upsell_opportunity")
        if upsell:
            upsell_section = f"""
            <div class="upsell">
              <h3>Upsell Opportunity Identified</h3>
              <p style="margin:0;color:#0c4a6e;">{upsell}</p>
            </div>"""
        else:
            upsell_section = ""

        # Service notes
        notes = service_data.get("findings", "")
        if photo.get("quality_notes"):
            notes += f"\n\nPhoto analysis: {photo['quality_notes']}"

        # Next steps
        next_steps = ""
        if service_data.get("follow_up_required"):
            next_steps = service_data.get("follow_up_notes", "Follow-up appointment recommended.")
        else:
            next_steps = "No immediate follow-up required. Client notified of next recommended visit."

        html = HTML_REPORT_TEMPLATE.format(
            business_name=business,
            report_id=report_id,
            date=datetime.utcnow().strftime("%B %d, %Y"),
            provider_name=provider,
            client_name=client,
            service=service_data.get("service_performed", ""),
            duration=f"{service_data.get('duration_mins', 'N/A')} mins",
            extra_fields=extra_fields,
            service_notes=notes,
            compliance_section=compliance_section,
            upsell_section=upsell_section,
            next_steps=next_steps
        )

        return html, report_id

    def create_stripe_invoice(self, client_email, client_name, service, amount_cents, business_name):
        """Creates and sends a Stripe Payment Link as the invoice."""
        if not stripe.api_key:
            logger.warning("Stripe not configured — invoice skipped.")
            return None

        try:
            product = stripe.Product.create(name=f"{service} — {business_name}")
            price = stripe.Price.create(unit_amount=amount_cents, currency="usd", product=product.id)
            link = stripe.PaymentLink.create(line_items=[{"price": price.id, "quantity": 1}])
            logger.info(f"Stripe invoice created: {link.url}")
            return link.url
        except Exception as e:
            logger.error(f"Stripe invoice failed: {e}")
            return None

    def send_report_email(self, to_email, client_name, report_html, report_id,
                           invoice_url=None, business_name=""):
        """Emails the service report (and invoice link) to the client via Resend."""
        if not self.resend_key:
            logger.warning("Resend not configured — email skipped.")
            return False

        invoice_block = ""
        if invoice_url:
            invoice_block = f'<p><strong>Invoice:</strong> <a href="{invoice_url}">Pay Now</a></p>'

        html_body = f"""
        <p>Hi {client_name},</p>
        <p>Thank you for your visit! Your service report is attached below.</p>
        {invoice_block}
        <p>See you next time!</p>
        <p>— {business_name} Team</p>
        """

        payload = {
            "from": f"{business_name} <{self.from_email}>",
            "to": [to_email],
            "subject": f"Your Service Report — {report_id}",
            "html": html_body,
            "attachments": [{
                "filename": f"service_report_{report_id}.html",
                "content": base64.b64encode(report_html.encode()).decode()
            }]
        }

        try:
            r = requests.post(
                "https://api.resend.com/emails",
                json=payload,
                headers={"Authorization": f"Bearer {self.resend_key}", "Content-Type": "application/json"}
            )
            if r.status_code in [200, 201]:
                logger.info(f"Report emailed to {to_email}")
                return True
            logger.error(f"Resend error: {r.text}")
            return False
        except Exception as e:
            logger.error(f"Report email failed: {e}")
            return False

    def process_field_submission(self, submission):
        """
        Main entry point. Called when a provider submits a field report.
        submission: {
          business_name, provider_name, client_name, client_email,
          niche, voice_note, image_path (optional),
          service_amount_cents, pet_name (vet), species (vet)
        }
        """
        business = submission.get("business_name", "")
        niche = submission.get("niche", "veterinary clinic")
        logger.info(f"Processing field submission for {business} from {submission.get('provider_name', '')}")

        # 1. Parse voice note
        voice_data = self.transcribe_voice_note(submission.get("voice_note", ""))

        # 2. Analyze photo if provided
        photo_data = {}
        if submission.get("image_path"):
            photo_data = self.analyze_job_photo(submission["image_path"])

        # 3. Build report data
        report_data = {
            "business_name": business,
            "provider_name": submission.get("provider_name", ""),
            "client_name": submission.get("client_name", ""),
            "service_data": voice_data,
            "photo_analysis": photo_data,
            "pet_name": submission.get("pet_name", ""),
            "species": submission.get("species", "")
        }

        # 4. Generate HTML report
        report_html, report_id = self.generate_report(report_data, niche)

        # 5. Save report locally
        safe_client = submission.get("client_name", "client").lower().replace(" ", "_")
        out_dir = f"./leads_generated/reports/{safe_client}"
        os.makedirs(out_dir, exist_ok=True)
        report_path = f"{out_dir}/{report_id}.html"
        with open(report_path, "w", encoding="utf-8") as f:
            f.write(report_html)

        # 6. Create Stripe invoice
        invoice_url = None
        if submission.get("service_amount_cents") and submission.get("client_email"):
            invoice_url = self.create_stripe_invoice(
                client_email=submission["client_email"],
                client_name=submission.get("client_name", ""),
                service=voice_data.get("service_performed", "Service"),
                amount_cents=submission["service_amount_cents"],
                business_name=business
            )

        # 7. Email report + invoice to client
        if submission.get("client_email"):
            self.send_report_email(
                to_email=submission["client_email"],
                client_name=submission.get("client_name", ""),
                report_html=report_html,
                report_id=report_id,
                invoice_url=invoice_url,
                business_name=business
            )

        # 8. Log to Supabase
        if self.db:
            try:
                self.db.table("field_reports").insert({
                    "report_id": report_id,
                    "business_name": business,
                    "niche": niche,
                    "provider": submission.get("provider_name", ""),
                    "client_name": submission.get("client_name", ""),
                    "service": voice_data.get("service_performed", ""),
                    "has_upsell": bool(voice_data.get("upsell_opportunity")),
                    "invoice_url": invoice_url,
                    "timestamp": datetime.utcnow().isoformat()
                }).execute()
            except Exception as e:
                logger.warning(f"Supabase log failed: {e}")

        logger.info(f"Field report complete: {report_id} saved to {report_path}")
        return {"report_id": report_id, "report_path": report_path, "invoice_url": invoice_url}


if __name__ == "__main__":
    agent = FieldReportAgent()
    test = {
        "business_name": "Austin Urban Veterinary Center",
        "provider_name": "Dr. Johnson",
        "client_name": "Sarah Miller",
        "client_email": "sarah@example.com",
        "niche": "veterinary clinic",
        "pet_name": "Bella",
        "species": "Dog",
        "voice_note": "Completed wellness exam on Bella, a 3-year-old female Lab. Weight 52 pounds, slightly overweight. Administered rabies and DHPP vaccines. Noted early tartar buildup on rear molars. Recommended dental cleaning within 6 months. Client asked about joint supplements for aging dogs — good upsell opportunity. All vitals normal. No follow-up required unless owner notices behavioral changes.",
        "service_amount_cents": 18500
    }
    result = agent.process_field_submission(test)
    print(json.dumps(result, indent=2))
